/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Signer,
  utils,
  Contract,
  ContractFactory,
  PayableOverrides,
  BigNumberish,
} from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../../common";
import type {
  TestContract2,
  TestContract2Interface,
} from "../../../contracts/Deploy.sol/TestContract2";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_x",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_y",
        type: "uint256",
      },
    ],
    stateMutability: "payable",
    type: "constructor",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "value",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "x",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "y",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x6080604052336000806101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908373ffffffffffffffffffffffffffffffffffffffff160217905550346001556040516102cd3803806102cd833981810160405281019061006991906100b9565b816002819055508060038190555050506100f9565b600080fd5b6000819050919050565b61009681610083565b81146100a157600080fd5b50565b6000815190506100b38161008d565b92915050565b600080604083850312156100d0576100cf61007e565b5b60006100de858286016100a4565b92505060206100ef858286016100a4565b9150509250929050565b6101c5806101086000396000f3fe608060405234801561001057600080fd5b506004361061004c5760003560e01c80630c55699c146100515780633fa4f2451461006f5780638da5cb5b1461008d578063a56dfe4a146100ab575b600080fd5b6100596100c9565b6040516100669190610118565b60405180910390f35b6100776100cf565b6040516100849190610118565b60405180910390f35b6100956100d5565b6040516100a29190610174565b60405180910390f35b6100b36100f9565b6040516100c09190610118565b60405180910390f35b60025481565b60015481565b60008054906101000a900473ffffffffffffffffffffffffffffffffffffffff1681565b60035481565b6000819050919050565b610112816100ff565b82525050565b600060208201905061012d6000830184610109565b92915050565b600073ffffffffffffffffffffffffffffffffffffffff82169050919050565b600061015e82610133565b9050919050565b61016e81610153565b82525050565b60006020820190506101896000830184610165565b9291505056fea26469706673582212209d31d00a4eec1ec609792099e03be9d6211a320d86917d76fed93106fd5c91d764736f6c63430008180033";

type TestContract2ConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: TestContract2ConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class TestContract2__factory extends ContractFactory {
  constructor(...args: TestContract2ConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    _x: PromiseOrValue<BigNumberish>,
    _y: PromiseOrValue<BigNumberish>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<TestContract2> {
    return super.deploy(_x, _y, overrides || {}) as Promise<TestContract2>;
  }
  override getDeployTransaction(
    _x: PromiseOrValue<BigNumberish>,
    _y: PromiseOrValue<BigNumberish>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(_x, _y, overrides || {});
  }
  override attach(address: string): TestContract2 {
    return super.attach(address) as TestContract2;
  }
  override connect(signer: Signer): TestContract2__factory {
    return super.connect(signer) as TestContract2__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): TestContract2Interface {
    return new utils.Interface(_abi) as TestContract2Interface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): TestContract2 {
    return new Contract(address, _abi, signerOrProvider) as TestContract2;
  }
}
