/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { HelloWorld } from "./HelloWorld";
export type { MyCoin } from "./MyCoin";
export type { OnlyOwner } from "./OnlyOwner";
