/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as ballotSol from "./Ballot.sol";
export type { ballotSol };
export type { HelloWorld } from "./HelloWorld";
export type { MyCoin } from "./MyCoin";
export type { MyNFT } from "./MyNFT";
export type { OnlyOwner } from "./OnlyOwner";
