/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as ballotSol from "./Ballot.sol";
export type { ballotSol };
import type * as callSol from "./Call.sol";
export type { callSol };
import type * as createSol from "./Create.sol";
export type { createSol };
import type * as deploySol from "./Deploy.sol";
export type { deploySol };
import type * as eventSol from "./Event.sol";
export type { eventSol };
import type * as miniProxySol from "./MiniProxy.sol";
export type { miniProxySol };
import type * as upgradeSol from "./Upgrade.sol";
export type { upgradeSol };
export type { HelloWorld } from "./HelloWorld";
export type { MyCoin } from "./MyCoin";
export type { MyNFT } from "./MyNFT";
export type { OnlyOwner } from "./OnlyOwner";
export type { Test } from "./Test";
export type { Wallet } from "./Wallet";
