/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export interface TestInterface extends utils.Interface {
  functions: {
    "num()": FunctionFragment;
    "testAssert()": FunctionFragment;
    "testRequire(uint256)": FunctionFragment;
    "testRevert(uint256)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "num" | "testAssert" | "testRequire" | "testRevert"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "num", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "testAssert",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "testRequire",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "testRevert",
    values: [PromiseOrValue<BigNumberish>]
  ): string;

  decodeFunctionResult(functionFragment: "num", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "testAssert", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "testRequire",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "testRevert", data: BytesLike): Result;

  events: {};
}

export interface Test extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: TestInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    num(overrides?: CallOverrides): Promise<[BigNumber]>;

    testAssert(overrides?: CallOverrides): Promise<[void]>;

    testRequire(
      _i: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    testRevert(
      _i: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[void]>;
  };

  num(overrides?: CallOverrides): Promise<BigNumber>;

  testAssert(overrides?: CallOverrides): Promise<void>;

  testRequire(
    _i: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  testRevert(
    _i: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<void>;

  callStatic: {
    num(overrides?: CallOverrides): Promise<BigNumber>;

    testAssert(overrides?: CallOverrides): Promise<void>;

    testRequire(
      _i: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    testRevert(
      _i: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    num(overrides?: CallOverrides): Promise<BigNumber>;

    testAssert(overrides?: CallOverrides): Promise<BigNumber>;

    testRequire(
      _i: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    testRevert(
      _i: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    num(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    testAssert(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    testRequire(
      _i: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    testRevert(
      _i: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
