/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IEventSubscriber,
  IEventSubscriberInterface,
} from "../../../contracts/Event.sol/IEventSubscriber";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "value",
        type: "uint256",
      },
    ],
    name: "handleTransferEvent",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IEventSubscriber__factory {
  static readonly abi = _abi;
  static createInterface(): IEventSubscriberInterface {
    return new utils.Interface(_abi) as IEventSubscriberInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IEventSubscriber {
    return new Contract(address, _abi, signerOrProvider) as IEventSubscriber;
  }
}
